### ISSUE TITLE
Mobile getUserMedia

### ISSUE THREAD

**Issue by clintberry** [addyosmani/getUserMedia.js#16]
I think it would be cool to add mobile support for phoneGap. It would be awesome to use one function that worked on every device! Do you think that is even feasible? If so, I will start looking into it.

**Comment by addyosmani** [comment]
You could potentially check if you're within a phoneGap environment and then defer back to http://docs.phonegap.com/en/1.0.0/phonegap_camera_camera.md.html. That API supports success, fail etc. It's certainly theoretically possible. Feel free to research further :)

**Comment by clintberry** [comment]
Nice! I'll fork and let you know.
