### ISSUE TITLE
Error in Chrome Canary (20.0.1132.1)

### ISSUE THREAD

**Issue by samdutton** [addyosmani/getUserMedia.js#4]
I'm getting the following error in Chrome Canary in the call to getUserMedia(): 

```
Uncaught Error: TYPE_MISMATCH_ERR: DOM Exception 17
```

I think this is because getUserMedia() in Chrome Canary now takes an object.

(I _think_ the problem is as described below, but apologies if my diagnosis is wrong...)

In the code that sets getUserMediaOptions, you check the value of optionStyle.string. This defaults to true, so if getUserMedia() takes an object, this will be true. As far as I can see, this means that the else block will never be called. In other words, options will be set to a string.

I think the first if should be if (optionStyle.string && !optionStyle.object).

  if (optionStyle.string) {
                if (options.video && options.audio) {
                    getUserMediaOptions = 'video, audio';
                } else if (options.video) {
                    getUserMediaOptions = 'video';
                } else if (options.audio) {
                    getUserMediaOptions = 'audio';
                }
            } else if (optionStyle.object) {
                if (options.video) {
                    getUserMediaOptions.video = true;
                }
                if (options.audio) {
                    getUserMediaOptions.audio = true;
                }
            }

**Comment by samdutton** [comment]
With the changes to getUserMedia() in Chrome Canary a few days ago, permission is now requested when getUserMedia() is called. 

This means that with the shim, permission is requested twice: once in the try block, and once when navigator.getUserMedia_ is called. 

Maybe the code could be restructured _just_ to use the try block?

**Comment by samdutton** [comment]
One other small thing.

Because getUserMedia is declared with this line:

  var getUserMediaOptions;

i.e it's undefined so this doesn't work:

if (options.video) {
                    getUserMediaOptions.video = true;

Adding _getUserMediaOptions = {};_ should fix this.

**Comment by addyosmani** [comment]
This has now been fixed with the latest, which also support the Firefox nightlies gUM implementation \o/
