### ISSUE TITLE
TYPE_MISMATCH_ERROR for options['video'] = true and options['audio'] = false

### ISSUE THREAD

**Issue by jywarren** [addyosmani/getUserMedia.js#7]
I get:

```
Uncaught Error: TYPE_MISMATCH_ERR: DOM Exception 17 getUserMedia.js:112
```

in Chrome 21 (and 20, though i can't test that anymore, sorry) - Version 21.0.1180.57

and then:

```
Uncaught TypeError: Not an object.
```

for my statement "getUserMedia(this.options, this.success, this.deviceError)"

However, after banging my head against the keyboard for a few days, and tracing the options format detection, i found that the version which works in your demo asks for both video and audio -- so when i did video=true and audio=true (the latter was false before), it works!

I would keep chasing the bug past this point but i'm kind of desperate to return to coding my app (http://spectralworkbench.org/capture). But if you have specific questions, i'd love to help; this library is rad.

**Comment by addyosmani** [comment]
Any help with compatibility would very much be appreciated. As gUM has been getting API revisions at different vendor levels, I've been trying to keep up with them but the library is probably a few tweaks out of being cross-browser again. I think the change you recommended above as well as a tweak to support gUM in the FireFox nightlies may be all that's left to get it back to complete functionality. 

I won't have a chance to fix the issues this weekend, but I'm happy to accept any PRs :) Will take another look this coming week. Thanks for reporting!

**Comment by addyosmani** [comment]
Thanks for this fix too, @franzenzenhofer.

**Comment by jywarren** [comment]
wow excellent; thanks -- will test shortly
